# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
